# Generated by Django 4.0.4 on 2022-06-18 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Название подкатегории')),
                ('category_slug', models.SlugField(max_length=250, verbose_name='slug поле подкатегории')),
                ('image', models.ImageField(blank=True, upload_to='images/shop')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'db_table': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название марки')),
                ('image', models.ImageField(upload_to='images/mark', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=250, verbose_name='Имя для категории')),
                ('mark', models.CharField(max_length=250, verbose_name='Марка')),
                ('list_slug', models.SlugField(max_length=255, unique=True, verbose_name='slug для категории')),
                ('image', models.ImageField(blank=True, upload_to='images/shop')),
            ],
            options={
                'verbose_name_plural': 'Категории запчастей',
                'db_table': 'Категория запчасти',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Типы деталей',
                'db_table': 'Типы деталей',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Оригинальный номер')),
                ('article_second', models.CharField(max_length=255, verbose_name='Коментарий')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название детали')),
                ('part_slug', models.SlugField(max_length=250, verbose_name='Слаг')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('image', models.ImageField(upload_to='images/shop')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='Категория')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='catalog.type')),
            ],
            options={
                'verbose_name_plural': 'Детали',
                'db_table': 'Деталь',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.CharField(max_length=2000, verbose_name='Запчасти')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая цена')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер')),
                ('orient', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ориентир')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'db_table': 'Заказ',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='part_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='catalog.partlist', verbose_name='подкатегория'),
        ),
    ]
