# Generated by Django 4.0.4 on 2022-06-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_article_second_type_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Типы деталей'},
        ),
        migrations.AlterModelTable(
            name='type',
            table='Типы деталей',
        ),
    ]
